# The Aurora's Avarice

This is a [monster of the week](https://evilhat.com/product/monster-of-the-week/) mystery. 

In this adventure the hunter's go to Skifry, a troubled Canadian mountain town.
It is the off season in October and work is under way to revamp the small mountain town to match the giant ski resort, The Aurora.
This is all through investments by Veil resorts, a massive mountain resort company.

The Daman siblings, owners of The Aurora are delighted by the investment and hope to sell the majority of their shares to retire early.

Everyone else in the town are unhappy with the destruction of their snowy mountain life.

However, it is the Bjorksons that have caused the recent deaths. 
If the building of new roads goes ahead in the town their business of electric taxis and transport will go bust, as the narrow roads ban all other powered forms of transport.
They will lose their monopoly.

They have transformed themselves into powerful human/ice worm hybrids by the consumption of Ice Worm eggs.
Additionally, they lure the one Juvenile Ice Worm to their victims with a drone projecting lights like the Aurora Borealis.

This Cult of Skyuss (Ski + Kyuss) has done little by killing road construction workers.
However, they have recently had a win.
Whilst transporting people around town they overheard that Jeff Daman (Ski resort family) was going skiing late at night.

## Suggested intro sequence

Jeff Daman is on the slopes late at night.
The aurora comes out causing Jeff to look at his smart watch.
He shrugs and sets off down the slope.
A large rumbling occurs, the snow is disturbed and Jeff screams followed by a large crunch.

## Hook

The Daman siblings, Ann & Dan, have called the hunters to investigate the death of their brother Jeff.
He was found on the ski slopes with large chunks bitten off him.
These bites are large and semi-circular like that of a large shark.

## Notes

- The cave of origins is where the ice worm eggs were found. It was uncovered by a large avalanche 9 months ago. The avalanche did not harm Skyfry or the resort. Deaths started 7 months ago.
- There are many undergound hot springs in the area, hence why the ice worm can survive here.