# Hal and the misison

At the start of this adventure the players & characters do not know where they are or how they happened to get there. Instead, they all awake from the same dream at the same time.

> As you wander through a breezeswept field, a crimson mist falls across your vision. Flashes of events, flashes of corrupted memories. The rain, that is you, falls into multiple rivers of red. The rivers near each other, but  always remain seperate. That is until the crimson mist falls once more. The rain stops. The banks between rivers corrode. 

>You are stones, waiting and waiting. Eventually, you brush off the moss and move. Born in a swirling chaos you became lost but found a vast blue calmness. 

>You are a Bull, forced to fight. You see your red blod and feel the rage inside yourself. 

> A beautiful music replaced by an unknown voice. They overlap and puncture each other creating an alluring yet dissonant cacophony. A lone figure stands in a dark field haunted by silhouettes.  

> A plague of toothed frogs. They descend upon an orchestra of crikets. As you and your fellows chirp in pain and fear, the slowest among you become food for the amphibians. Your saviours arrive. A Goat, a Fish, and a Torch bearer decimate the frogs with horns, scales, and fire. All are powerful but you feel the flames. It scorches your minds, the crimson mist replaced with a white flame. And with that the rivers reemerge as separate once more.

> You all awake in separate beds in a metal room. What do you do?

The dorm is sparse, containing beds and trunks for each character but little else. In their bunks lies their clothes and equipment. There is one door that unlocks and opens as they approach it. This leads to Hal's room.

## Hal's room

This large disc shaped room has many doors leading into it, one being from the character's room. In the middle lies a large cylindrical metal support with stairs connecting the upper and lower floor. Currently access to either floor is barred by larger metal slabs that line up with the floor and ceiling.

At the stairs' landing is a porthole into the cylinder. From this emits a firey light. The source if which is struggling fire. This fire's name is Hal, the fire elemental. The controller and current only source of power for this ship.

Hal will lock them in this room and not let them into any of the rooms.

## Hal

Hal is a smart fire elemental. It controls and powers the ship. it doesn't have the power to traverse between the planes and is weakened from its constant work of keeping the ship afloat and keeping the red ink at bay.

Hal recently spent much energy and time refining the red ink to make it safe to drink. Its experiments eventually worked but the worst of the crew are now dead, whether from combat, the effects of the red ink, or through Hal's experimentation.

Hal is exhausted and can barely talk, therefore it only speaks in a robotic manner in short sentences.  It does have a mission for the characters.

## Hal's Mission

> Go to the tower and find a functioning planar orb. Mine was stolen by Cappy, Dud, and Bobert. Find them and take it back with force. Do not drink the red ink.

> If you find any worthy candidates please invite them to join us at GAStEr.

Hal will provide them with 2 days of water and rations each and a compass that point back to them. It won't move the ship any closer to the tower afraid thet it will expire and therefore the HFC will become useless.

Hal cannot answer too many questions due to its exertions. However, if asked Hal can provide the following information:

- Cappy was the Bugbear Captain
- Dud was the Goblin 2nd mate
- Bobert was the Hobgoblin Engineer
- The red ink takes away memories and maybe more

Only once accepting the mission and taking their supplies, will HAL open the way to the deck so the characters can leave.
