# Cult of Skyuss

The Bjorks run the electric mini transport in town, the Skifry Ski Lifts.
They are the only form allowed in the town currently due to the narrow roads.
However, their monopoly may come to an end.
This company is run by the six brothers who comprise the entire cult.

1. __Igor__ (Black beard)
2. __Gregor__ (Ginger beard)
3. __Timor__ (Blond beard)
4. __Viktor__ (Grey beard)
5. __Nestor__ (Black peppered beard)
6. __Hektor__ (Purple beard)

Roll a d6 to see which brother picks up the hunters each time they use the Skifry ski lifts.

They found the cave of the Wrym, ate Snow worm eggs and lure the one Juvenile Ice Worm to disrupt the development.

They see the worm as their weapon whilst the worm sees them as its siblings who it will not harm.
However, it is a worm so it does not see the Cult as anything more than something to avoid.

## Motivation

They have the three below motivations depending on the scenario for them.

- _Scout_: to stalk, watch, and report.
  - They try to get info from people as they drive people around.
- _Cultist_: to save their own skin.
  - Machinations are to protect their business.
- _Brute_: to intimidate and attack.
  - Will intimidate people to not help the hunter via threats of not giving transport.
  - Will disguise themselves and attack the hunters and disrupt their investigation.
- _Assassin_: To kill the hunters
  - If they figure out what the hunters are doing they will try to  use the worm to kill them.

## Appearance

The 6 Bjork brother are all short but stout men.
They wrap up well in long colourful jumpers covered by a puffer vest.
Their heads are covered up by the combination of a big fluffly trapper hat and massive sprawling beard.
This is easily explained as it is quite cold in the electric cars since it is too expensive to heat them.

They wear sunglasses for snow blindness that allows them to hide their purple eyes.

It is nearly impossible to differentiate the brothers if not for the colour of their beards.

They give off a sickly sweet smell they try to mask with pine tree car air freshners and cheap cologne.

## Powers

- __Diamond interlocking bones__
  - They have near unbreakable bones.
  - Their bones have divided into smaller but interlocking bones. This allows them to fit through very tight spaces.
- __Increased strength__
  - Although they don't look it their strength is similar to the strongest people in the world.
- __Maw__
  _ They have large circular mouths with rows of diamond teeth.

## Weakness

- __Coldness__: They are very weak to the cold.
- __Bright colourful lights__: Will stun them into a stupor momentarily.

## Attack

- Punch: 1 harm, hand range.
- Bite: 3 harm, hand range. They need to pin the hunter down.

## Armour

- 1 armour due to some diamond patches on their skin.

## Harm capacity

- 5 harm capacity. Although the transformation has made them stronger in ways it has also made them easier to kill due to their unnatural features.

