# Locations & bystanders

## "Base camp"

_Point of no return_

A large parking lot at the base of the mountain.
This is where all cars and other out of town transport stop.
Two of __Skyfry's Ski lifts__ largest vehicles are generally always waiting here, a E-minbus and an E-van.
One of the __Bjork brothers__ in a small cabin waiting to use one or the other.

This is the first place the hunter's will arrive and so the first person they meet will be a Bjork brother.

As they travel up the winding road for an hour the first thing they will see of the town of Skifry is its town symbol on a welcome to sign.

If the hunters try to return to base camp before solving the mystery they will find the minibus & van have "broken down".
Unfortunately the normal Ski lift taxis can't make it down the steep road.

## The Aurora

_Crossroads_: To bring people, and things, together.

The Stylish brutalist architecture of the resort intensifies the beauty of the forest and mountain.
Instead of concrete the boxy buildings are covered in mirrors with borders of undulating multicoloured leds, like a gamers keyboard.
It must be a sight to behold when the Aurora is out.

In sharp contrast the insides contain beautiful wood work all over the woodne ceilings, walls, and flooring.
There are many electric fire pits.
There are plenty of windows not visible to the outside as they are one way mirrors.

All the amenities you can think of in a ski resort are present.
As the owners, the Damans, asked for help the hunters have each been given a premium suite with full access to amenities.
It helps that it is the off season so it is quiet anyway.

The place is heated by the natural hot water form the underground hot springs.

### The Damans

Ann and Dan Daman go around wearing blue and pink robes, when to jump in the spa or swimming pool at a moments notice.
They assure the hunters they would look a lot more professional in the busy season or with important people around.
They are both very blond, white and beautiful, think Barbie and Ken.

Dan likes to introduce himslef as Dan Da Man.
Ann gets very annoyed at this and says "It's pronounced Damon like Matt Damon, he visits every year".
They of course like to name drop famous celebrities, feel free to use real people and/or make up ones.



## Skifry

_Hub_: to reveal information

Town symbol is that of a purple dragon (wrym) on the snow with a beautiful Aurora Borealis in the sky.

Initially the town was founded due to the abundance of underground hot springs used for heat and now to generate electricity.


