# Skifry

_Hub_: to reveal information

Town symbol is that of a purple dragon (wrym) on the snow with a beautiful Aurora Borealis in the sky.

The town is a cozy Canadian town. Plenty of peaked top buildings covered in snow.

Initially the town was founded due to the abundance of underground hot springs used for heat and now to generate electricity.

## Church of Nyxmera

A church of the Primeval deity Nyxmera. The two-faced deity of night and day. It embodies drama, loving the light (comedy) and the dark (tragedy). It is forever watching and so wants interesting events to occur.

The vast majority of the town attend this church.

Note: In my world this relgion is normal, feel free to replace with a different church.

### Summer Night (she/her), cleric of Nyxmera

_Gossip_: to pass on rumours.

She wears a robe, one side is bright white whilst the other is black.

She is very cheery with a very dark sense of humour.

## The Yert

A gear shop run by the Yerts. The hunters can buy a bunch of gear here like drones, night vision goggles, snow gear etc.

### Bob & Susi Yert

_Witness_: to reveal information

They are both amenable but unwilling to discuss current events in details. They are loyal to the Bjorksons but don't know what they are actually doing.

If pressed or threatened they may reveal that the Bjorksons bought a very fancy drone a few months back.

## Hospital & morgue

### Dr Mordecai Tryst (he/him), morgue man

_Detective_: to rule out explanations.

A morose tired man. Did the autopsies on the various victims. None of the bodies are with him so the hunters only have his word to go on.

He doesn't like these murders and wants them to be stopped.

## Indeginous centre

A centre to display the history of indigenious tribes of Canada.

### Charlie (they/them), curator and story teller

_Witness_: To reveal information.

A friendly story teller with many paper cuts on their fingers.

They can tell the hunters many stories of various mythology and creatures.

Will only tell the hunters the story of the ice worm if the hunters know it is an ice worm they are dealing with.

> The native Waawate & Icelandic Jokla were a warlock pair of great power. They vanquished the mighty ice worm. Waawate summoned the Northern lights to attract the beast. Then Jokla encased it in ice.


## Misc

### Mr Plum (he/him)

_Witness_: to reveal information

A plumber with a large moustache and cap emblazoned with a plum.

The hunters will most likely seem him multiple times around town as there are many plumbing issues.
Little bits of diamonds are shredding water pipes. 
He will happily complain about this to anyone who asks.

These bits of diamonds are coming from the Ice worm which frequents the hot springs to keep warm.



