# Encounters in the Forgetting realms

This section contains various encounters as the characters traverse the forgetting realm to the tower. Whilst they travel you can time skip, these time skips are preceded by the red ink falling as rain.

## The Forgetting realms

As they arrive on the deck of HFC. The characters see the following:

> Going above decks you expect the sun to blind you, unfortunately you are dissapointed. Instead a pitch black sky greets you. Rivers of red ink in the blackness  the only source of a dull crimson light. The rivers split and join forming a loose web emanating from a single point. The obsidian tower.

> This tower is the sole break in the horizon. The landscape consiting of a flat plain of cracked red dirt. It is still and silent, any noise absorbed by the ground or lost into the nether. Somehow you can breath the alien air, almost as if your body forgot what air it needs.

## Oblex Spawns as they leave the ship

The first encounter occurs after the have descended from HFC, via a sort of levitating platform, and moved 45ft away from it.

Red __Oblex Spawns__ (number of players times 1.5, rounded down) try to surprise and attack the characters.

They stealthily (suggested stealth roll of 15) follow the characters as puddles of red ink.

- If they are not detected they will surround the characters and rise into their humanoid like forms. Due to the time it takes to rise they won't have a surprise round.
- If detected they will all rise on one side of the characters. Dues to the time it takes to rise they will have disadvantage on their initiative check.

The red Oblexes are gelatinous beings in the form of humanoids. Their bodies made of the rusted dirt and red ink.

As the characters fight these humanoid red Oblexes they will notice they have familiar faces, although they can't properly recall who they were. Unbeknownst to the characters these red Oblexes were created from the minds and memories of their fellow crew members. They are only spawn and so cannot communicate. They attack thinking they can steal the character's bodies.

Once the fight is over:

> As the last oblex drains into the cracks of the earth you hear the patter of rain on the hard ground. 

## Sylgar the talking fish

> You wake to patter of rain on a corrugated iron roof. In makeshift beds you quickly scan your surroundings. This inspection is quick as the only source of light within this small shed is an __Iron Golem__. The Ash covered Golem, hunched over a work table, stops its work and turns towards you all.

> Within its chest a fire rages, viewable by a porthole. The light illuminates the area revealing stacks of pages and empty ink pots. Lieing were you expect to be massive helmet on Golem, instead lays a glass bowl of slightly red water. Within this water a large koi. It speaks "Oh! you are all awake! Hello, I'm Sylgar."

Sylgar invited the mind addled characters into their house and provided them with some if his purified water. He knows a quick way to Towerville. 

Sylgar will help them get to the tower quickly if they carry out a task for him. He asks them to travel to a nearby well protected by Jen the __Troll__.  

Walking toward the tower they 

* The red ink begins to fall forcing the players into a rusted corrugated shack
* Inside is __Sylgar__ the talking fish
* Sylgar was previously owned by the Xanathar but now has sentience
* Is in a fish bowl mounted on top of an __iron golem__ with a heart of fire
* Fish bowl water is slightly red
* Pages and pages of ramblings in red ink with quills and mostly empty ink pots
* Has an odd looking machine with a funnel on one end and a spout on the other, looks extremely pristine.
* __Sylgar__ is scared of the outside and asks group to go to a well protected by a Troll (__Jen__)
* Needs ink from the well
* Knows a quick way to Towerville
* Sylgar will let group rest for the "night" before travelling to the Troll well
* Sylgar will not leave as his shack has been raided recently and he needs to protect it.
* Good candiate as a recruit.

## Jen the Troll

* About an hour walk from Sylgar's
* A large blue and green Troll with long matted hair
* Jen is feeling the memory effects of the ink but not the physical ailments due to trolls' regenerative abilities
* She guards the well as it is a good source of water for her.
* Will give them a bucket if they each tell her one of their memories
* A good time for each player to elaborate on a part of their backstory or they can try to lie but she will try (poorly) to determine if someone is lying.

##  Vegepygmy & thorny attack at Sylgar's
* Dud (an __Oblex Spawn__ now) attacks with Vegepygmy and Thorny's
* Dud will stay far back on their own Thorny, not attack and run off to Towerville when things seem to be going bad
* A __Thorny__ being ridden by a __vegepygmy__ per player
* They have been kiting Sylgar with Thornys using dash to stay out of range and Vegepgymys using spears (6dmg)
* Sylgar is down to 60hp (ignore resistance to non magical weapons)
* If Vegepygmy killed the Thorny will run to attack closest enemy with melee
* Ignore regeneration ability of Thorny and Vegepygmy due to the ink

## Travel to Towerville
* Hopefully the players will want to follow Dud who is heading to Towerville to report back the the Oblexed Cappy and Bobert.
* With some magic he can transfer some of the flames to the dead Thornys to give them limited life.(enough to get to Towerville but not back.
* Make a sled from corrugated iron.
* Slygar will refuse to come as needs to get the well water processed soon.

## End session & gain a level


